### PR TITLE
feat(compiler): Add gcc version 12 support to the toolchain

### PR DESCRIPTION
**Pull request by bgianfo**

### CODE REVIEW

**Comment by bgianfo** [comment]
@silvergasp any chance you can take a look?

**Comment by bgianfo** [comment]
I saw you kicked off allowed actions to execute, but the linux and macos actions failed. I just pushed a commit that should fix CI for the repository in general.

**Comment by silvergasp** [comment]
Sorry, I got a bit burnt out with open source stuff and have been taking a break for a few months, just starting to sort through the backlog now.

**Comment by silvergasp** [comment]
Hmm ok, it looks like its failing the windows build now. I might just disable that in the CI as windows was never properly supported anyway.

**Pull request merged**
