### PR TITLE
platforms: Add cortex-m33 platforms

### PR DESCRIPTION
**Pull request by afoxley**

### CODE REVIEW

**Comment by silvergasp** [comment]
Sorry, I'm unsure what the issue is with the CI it's seemingly getting queued but then timing out. I'll take a better looking at this on my local machine sometime over the next week.

**Comment by afoxley** [comment]
Friendly review ping, thanks!

**Comment by afoxley** [comment]
Looks like pull request 70 fixes the CI issues: https://github.com/bazelembedded/bazel-embedded/pull/70/commits/fd26ecc9bfb20a38ae43eab56cbeef44431af52a

**Comment by silvergasp** [comment]
Sorry, I was getting a little burnt out and have been taking a break from open-source stuff for a while. Just getting back into it, and sorting through my backlog now :)

**Pull request merged**
